# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dab4d8be2fc5869b2e36b767c7edb6b8"
name = "Custom_app"
handle = "custom_app-58"
application_url = "https://products-partially-qualifying-harper.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extensionsbility-check.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://products-partially-qualifying-harper.trycloudflare.com/auth/callback",
  "https://products-partially-qualifying-harper.trycloudflare.com/auth/shopify/callback",
  "https://products-partially-qualifying-harper.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
